server:
  port: 9002
spring:
  shardingsphere:
    datasource:
      names:
        master,slave
      # ä¸»æ•°æ®æº
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.213.128:3306/takeout?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
        username: root
        password: root
      # ä»æ•°æ®æº
      slave:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.213.138:3306/takeout?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
        username: root
        password: root
    masterslave:
      # è¯»å†™åˆ†ç¦»é…ç½®
      load-balance-algorithm-type: round_robin #è½®è¯¢ï¼Œä»åº“ä¸€ä¸ªæ¥ç?ä¸?ä¸ªçš„ä¸?
      # æœ?ç»ˆçš„æ•°æ®æºåç§?
      name: dataSource
      # ä¸»åº“æ•°æ®æºåç§?
      master-data-source-name: master
      # ä»åº“æ•°æ®æºåç§°åˆ—è¡¨ï¼Œå¤šä¸ªé€—å·åˆ†éš”
      slave-data-source-names: slave
    props:
      sql:
        show: true #å¼?å¯SQLæ˜¾ç¤ºï¼Œé»˜è®¤false
  main:
    allow-bean-definition-overriding: true
  #redisæ•°æ®æº?
  redis:
    host: 192.168.213.128
    port: 6379
    database: 0
    #ç¼“å­˜æœ‰æ•ˆæ—¶é—´
  cache:
    redis:
      time-to-live: 1800000
  mvc:
    hiddenmethod:
      filter:
        enabled: true
#é‚®ç®±
  mail:
    host: smtp.qq.com
    username: 2860285053@qq.com
    password: ajqmtiykwechdcij
#MPé…ç½®
mybatis-plus:
  configuration:
    #åœ¨æ˜ å°„å®ä½“æˆ–è€…å±æ€§æ—¶ï¼Œå°†æ•°æ®åº“ä¸­è¡¨åå’Œå­—æ®µåä¸­çš„ä¸‹åˆ’çº¿å»æ‰ï¼ŒæŒ‰ç…§é©¼å³°å‘½åæ³•æ˜ å°?
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
#å›¾ç‰‡åœ°å€
reggie:
  path: C:/img/




